### ISSUE TITLE
Support forum link is out of date

### ISSUE THREAD

**Issue by wr-dev** [outfielddigital/konstrukt-documentation#2]
Hi Matt,

Looking at using another one of your awesome Umbraco projects.

Was looking here: https://github.com/outfielddigital/konstrukt

And noticed that the link for the support forum goes to here: https://our.umbraco.com/packages/website-utilities/konstrukt/konstrukt-support/

Rather than here: https://our.umbraco.com/packages/backoffice-extensions/konstrukt/konstrukt-support/

Just thought I'd let you know. 

Cheers!

Tom

**Comment by mattbrailsford** [comment]
Thanks for highlighting this. The link has now been updated 👍
