### ISSUE TITLE
is the '[PrimaryKeyColumn]' attribute needed in pocos?

### ISSUE THREAD

**Issue by ribsdigital** [outfielddigital/konstrukt-documentation#5]
hey there matt,

we wanted to check if the `[PrimaryKeyColumn]` is needed required in pocos?

from the docos, the 'id' column has the attribute:

[https://docs.getkonstrukt.net/guides/creating-your-first-integration#set-up-your-model](https://docs.getkonstrukt.net/guides/creating-your-first-integration#set-up-your-model)

```
using NPoco;
using Umbraco.Cms.Infrastructure.Persistence.DatabaseAnnotations;

[TableName("Person")]
[PrimaryKey("Id")]
public class Person
{
    [PrimaryKeyColumn]
    public int Id { get; set; }
    public string Name { get; set; }
    public string JobTitle { get; set; }
    public string Email { get; set; }
    public string Telephone { get; set; }
    public int Age { get; set; }
    public string Avatar { get; set; }
}
```

the attribute comes from the umbraco core `Umbraco.Cms.Infrastructure.Persistence.DatabaseAnnotations`.

the reason we ask is that we'll be using these pocos in other areas of our project that doesn't use umbraco...

we've experimented with removing the attribute and it doesn't appear to cause any issues with crud opperations...

if you could let us know if it's needed, that'd be great 👍

**Comment by mattbrailsford** [comment]
Hey @ribsdigital, I don't think it's essential actually. I think this comes from Umbraco and some of their `Sql` extensions that generate Sql dynamically from a model but I don't believe we rely on those really.

I'm sure if we did need them it would have blown up pretty quickly so I think you should be ok to not use it. But if you do find an issue with it, let me know and I'll see if I can work around it. I don't think we should really need to.
