### ISSUE TITLE
the 'delete' menu action results in a 'section cannot be null' console error

### ISSUE THREAD

**Issue by ribsdigital** [outfielddigital/konstrukt-documentation#6]
hi matt,

we've been trying to set up a new [menu item](https://docs.getkonstrukt.net/api/menu-items) and along the way we've noticed that the 'delete' action is throwing a console error.

clicking the delete button logs `section cannot be null` and the entity isn't deleted:

![image](https://user-images.githubusercontent.com/22835873/161861823-6396d8c3-dab7-4644-a170-062019c6b4d1.png)

we get the same issue with the menu item we're attempting to set up:

![image](https://user-images.githubusercontent.com/22835873/161862058-61be44dd-03c7-478c-b402-c9cd969e4a8c.png)

deleting at the list view level works:

![image](https://user-images.githubusercontent.com/22835873/161862151-9c31a42f-ac9c-44d3-aaf8-4b0121c7e164.png)

however the following is logged in the console:

```
XML Parsing Error: no element found
Location: https://localhost:44369/umbraco/backoffice/konstrukt/konstruktapi/DeleteEntity?collectionAlias=person&id=1
Line Number 1, Column 1:
```

this is happening with v1.0.1 and the v1.0.2-beta0004 versions that we've been using.

we're using konstrukt in umbraco v9.3.1, could this be a backoffice update issue? if you could let us know on the above, that'd be grand 👍

**Comment by mattbrailsford** [comment]
@ribsdigital good spot. There should be a 1.0.2-beta0008 on our unstable feed now with a fix for this. Do let me know if this resolves it for you.

**Comment by ribsdigital** [comment]
hi @mattbrailsford we have a winner! yup, console errors gone and the delete menu now works as expected 👍 

we've also got our 'duplicate form' menu item working! however... there is one thing that's eluding us...

we can't seem to set the 'title' of the overlay that comes in from the left?!

![image](https://user-images.githubusercontent.com/22835873/162111585-45f23c6f-fac1-4891-92ed-e2e8c85bb644.png)

to get this working, we've robbed quite a bit of code from `App_Plugins\Konstrukt\backoffice\konstrukt\delete.html` and `App_Plugins\Konstrukt\backoffice\konstrukt\delete.controller.js` but we can't see anything in there that would set the title...

**Comment by mattbrailsford** [comment]
Hey @ribsdigital 

If you review the docs here on menu items https://docs.getkonstrukt.net/api/menu-items when you need to launch a dialog view you should use the `KonstruktMenutItemDialogViewAction` action which has a `title` parameter that sets the dialogs title.

**Comment by ribsdigital** [comment]
thanks @mattbrailsford works a treat 👍
